services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883 #default mqtt port
      - 8081:8081 #default mqtt port for websockets
    volumes:
      - ./Config/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./Config/config:/mosquitto/config:rw
      - ./Config/data:/mosquitto/data:rw
      - ./Config/log:/mosquitto/log:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mqtt-https.entrypoints=websecure"
      - "traefik.http.routers.mqtt-https.rule=Host(`mqtt.vanko.be`)"
      - "traefik.http.services.mqtt-https.loadbalancer.server.port=8081"
      - "traefik.http.routers.mqtt-https.tls=true"
      - "traefik.http.routers.mqtt-https.tls.certresolver=cloudflare"
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
