services:
  grafana:
    image: grafana/grafana:9.3.6
    container_name: grafana
    user: "0:0"
    ports:
      - 3000:3000
    volumes:
      - ./Config/data:/var/lib/grafana
      - ./Config/config:/etc/grafana
      - ./Config/log:/var/log/grafana
      - ./Config/config/grafana.ini:/etc/grafana/grafana.ini
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:?error}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:?error}
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entryPoints=websecure
      - traefik.http.routers.grafana.rule=Host(`grafana.vanko.be`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certResolver=cloudflare
    networks:
      - frontend

networks:
  frontend:
    external: true
